### PR TITLE
fixed loading and maybe jumping page

### LINKED ISSUE #539: BUG: Kopier svar fra annet skjema UI er scuffed

### PR DESCRIPTION
**Pull request by starheim98**
## Background
Buggy loading other contexts and jumping page

Resolves #issue-this-pr-resolves
#539

### CODE REVIEW

File: frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx [hunk 1]
```diff
@@ -1,27 +1,28 @@
...
     useFetchAllContexts();
 
   const contextsForTable: Context[] =
     contexts?.filter((context) => context.tableId === tableId) ?? [];
 
-  if (!contexts || contexts.length === 0) {
-    return null;
-  }
+  const isDisabled = contextsForTable.length === 0;
+  console.log(contextsIsLoading);
```
Comment (chribjel) [inline frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx]:
```suggestion
```

**Review by chribjel — APPROVED** [review]
